# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa4cea1b511215ac4cf023692f62af1d8a9fbe277756dc4c441515038267467910b85e22c4707549a62f01f86394ca5d344c4dda9a9de627a4640505ee6107cb

test:
  secret_key_base: 126a40cbe595cba2b64223d7ff0c37cd8a04c1f9bf94ce71869b3c6820bba670e522d89f11838ba492a789309921261132d3ea7cf5a5a3621b8479e4ae9c9678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
